DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS quote;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  fname TEXT NOT NULL,
  lname TEXT NOT NULL,
  ZIP INTEGER NOT NULL,
  DOB TEXT NOT NULL,
  quote FLOAT NOT NULL
);

CREATE TABLE quote (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  six_month_quote FLOAT NOT NULL,
  FOREIGN KEY (user_id) REFERENCES user (id)
);
